development: &development
  adapter: postgresql
  host: localhost
  database: weddingGuests_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: weddingGuests_test
  encoding: unicode